-- 코멘트 추가 (나중에 봐도 헷갈리지 않게 관리용)
COMMENT ON COLUMN SEARCH_TREND_COLD.SEARCH_INDEX IS '키워드 그룹: 감기, 목감기, 코감기';
COMMENT ON COLUMN SEARCH_TREND_ASTHMA.SEARCH_INDEX IS '키워드 그룹: 천식, 벤토린, 네블라이저';

CREATE OR REPLACE VIEW VW_ST2PR AS
SELECT
    T.DIST_CODE,
    T.MEASURE_DATE,
    T.POP_TOTAL,
    T.COLD_CNT_D0,
    T.ASTHMA_CNT_D0,
    C.SEARCH_INDEX AS COLD_SEARCH_IDX,
    A.SEARCH_INDEX AS ASTHMA_SEARCH_IDX
FROM TRAIN_SET T

INNER JOIN SEARCH_TREND_COLD C ON T.MEASURE_DATE = C.MEASURE_DATE
INNER JOIN SEARCH_TREND_ASTHMA A ON T.MEASURE_DATE = A.MEASURE_DATE;