-- 기존 테이블 삭제
DROP TABLE DISTRICT_CODE        CASCADE CONSTRAINTS;
DROP TABLE AIR_QUALITY_HOURLY   CASCADE CONSTRAINTS;
DROP TABLE PATIENT_CNT_DAILY    CASCADE CONSTRAINTS;
DROP TABLE AGE_STATS_QUARTERLY  CASCADE CONSTRAINTS;
DROP TABLE GDRP_PER_CAPITA      CASCADE CONSTRAINTS;
DROP TABLE GRDP_BY_INDUSTRY     CASCADE CONSTRAINTS;
DROP TABLE ASTHMA_CNT_MONTYLY   CASCADE CONSTRAINTS;

-- 지역구 코드, 지역구 이름 매핑
CREATE TABLE DISTRICT_CODE (
    DIST_CODE   CHAR(5) NOT NULL,
    DIST_NAME   VARCHAR2(40) NOT NULL,

    CONSTRAINT PK_DISTRICT_CODE
        PRIMARY KEY (DIST_CODE)
);

-- 시간 단위 대기 질
CREATE TABLE AIR_QUALITY_HOURLY (
    MEASURE_TIME    DATE NOT NULL,
    DIST_CODE       CHAR(5) NOT NULL,

    PM10 NUMBER(10, 1),
    PM25 NUMBER(10, 1),
    TEMP NUMBER(10, 1),

    CONSTRAINT PK_AIR_QUALITY_HOURLY 
        PRIMARY KEY (MEASURE_TIME, DIST_CODE),
    CONSTRAINT FK_AIR_QUALITY_HOURLY
        FOREIGN KEY (DIST_CODE)
        REFERENCES DISTRICT_CODE(DIST_CODE)
);

-- 일단위 환자 수
CREATE TABLE PATIENT_CNT_DAILY (
    MEASURE_DATE    DATE NOT NULL,
    DIST_CODE       CHAR(5) NOT NULL,

    COLD_CNT    NUMBER,
    ASTHMA_CNT  NUMBER,

    CONSTRAINT PK_PATIENT_CNT_DAILY 
        PRIMARY KEY (MEASURE_DATE, DIST_CODE),
    CONSTRAINT FK_PATIENT_CNT_DAILY
        FOREIGN KEY (DIST_CODE)
        REFERENCES DISTRICT_CODE(DIST_CODE)
);

--연령별 통계
CREATE TABLE AGE_STATS_QUARTERLY (
    STD_YEAR    NUMBER(4) NOT NULL,
    STD_QT      NUMBER(1) NOT NULL,
    DIST_CODE   CHAR(5) NOT NULL,

    AGE_ORD NUMBER,
    AGE_GRP VARCHAR2(40),
    POP_CNT NUMBER,

    CONSTRAINT PK_AGE_STATS_QUARTERLY 
        PRIMARY KEY (STD_YEAR, STD_QT, DIST_CODE),
    CONSTRAINT FK_AGE_STATS_QUARTERLY
        FOREIGN KEY(DIST_CODE)
        REFERENCES DISTRICT_CODE(DIST_CODE)
);

-- 1인당 지역내총생산
CREATE TABLE GDRP_PER_CAPITA (
    STD_YEAR    NUMBER(4) NOT NULL,
    DIST_CODE   CHAR(5) NOT NULL,

    GRDP        NUMBER,
    GRDP_SHARE  NUMBER,
    EST_POP     NUMBER,
    GRDP_PC     NUMBER,
    GRDP_IDX    NUMBER,

    CONSTRAINT PK_GDRP_PER_CAPITA
        PRIMARY KEY (STD_YEAR, DIST_CODE),
    CONSTRAINT FK_GDRP_PER_CAPITA
        FOREIGN KEY(DIST_CODE)
        REFERENCES DISTRICT_CODE(DIST_CODE)
);

-- 경제활동별 지역내총생산 - 2020년 기준년 연쇄가격만 사용
CREATE TABLE GRDP_BY_INDUSTRY (
    STD_YEAR    NUMBER(4) NOT NULL,
    DIST_CODE   CHAR(5) NOT NULL,
    
    GRDP                NUMBER,
    NET_PROD_TAX        NUMBER,
    GROSS_VAL_ADDED     NUMBER,
    AGRI_FOREST_FISH    NUMBER,
    MINING              NUMBER,
    MANUFACTURING       NUMBER,
    ELEC_GAS_STEAM      NUMBER,
    CONSTRUCTION        NUMBER,
    WHOLESALE_RETAIL    NUMBER,
    TRANS_STORAGE       NUMBER,
    ACCOM_FOOD          NUMBER,
    INFO_COMM           NUMBER,
    FINANCE_INSUR       NUMBER,
    REAL_ESTATE         NUMBER,
    BIZ_SERVICE         NUMBER,
    PUBLIC_ADMIN        NUMBER,
    EDUCATION           NUMBER,
    HEALTH_SOCIAL       NUMBER,
    CULTURE_OTHER       NUMBER,

    CONSTRAINT PK_GRDP_BY_INDUSTRY
        PRIMARY KEY (STD_YEAR, DIST_CODE),
    CONSTRAINT FK_GRDP_BY_INDUSTRY 
        FOREIGN KEY (DIST_CODE) 
        REFERENCES DISTRICT_CODE(DIST_CODE)
);

-- 월 단위 연령별 천식 환자 진료 건수
CREATE TABLE ASTHMA_CNT_MONTYLY (
    STD_MONTH   DATE NOT NULL,
    DIST_CODE   CHAR(5) NOT NULL,

    GENDER      CHAR(6),
    AGE_GRP     VARCHAR(40),
    ASTHMA_CNT  NUMBER,

    CONSTRAINT PK_ASTHMA_CNT_MONTYLY
        PRIMARY KEY (STD_MONTH, DIST_CODE),
    CONSTRAINT FK_ASTHMA_CNT_MONTYLY
        FOREIGN KEY (DIST_CODE)
        REFERENCES DISTRICT_CODE(DIST_CODE)
);